# Generated by Django 3.1.4 on 2020-12-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='img', verbose_name='image'),
            preserve_default=False,
        ),
    ]
