# Generated by Django 3.1.4 on 2020-12-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
